### ISSUE TITLE
OPTS+=" --kd-ratio 1.0"

### ISSUE THREAD

**Issue by liuxy1103** [jongwooko/distillm#4]
I found that many baseline hyperparameters in the code are this, does it mean that the student network in the distillation process is only supervised by the teacher network without gt supervision?

**Comment by jongwooko** [comment]
Hi, thank you for careful reviewing our code.

As we reported in our paper, we only utilize the kd loss for all methods, instead of combining kd and lm loss that used in MiniLLM.

This is because our preliminary experimental results that fully use of kd loss showed higher performance than combining kd and lm loss.

**Comment by liuxy1103** [comment]
"We randomly select 14K samples for training and equally leave 500 samples for validation and testing, respectively. " Is that why your results are inconsistent with minillm? You're using different data.
